spring.application.name=Curso

spring.datasource.url=jdbc:mysql://localhost/calcados_api
spring.datasource.username=root
spring.datasource.password=root123

spring.output.ansi.enabled=ALWAYS

spring.web.error.include-stacktrace=never